version: "3"

volumes:
  dbbackups:
  postgis-data:
  tarantool:

services:
  tarantool:
    image: "drip_tarantool"
    ports:
      - "3301:3301"
    volumes:
      - tarantool:/var/lib/tarantool
    #   - $PWD/docker/tarantool_scripts/dripapp.lua:/opt/tarantool/dripapp.lua

  postgres:
    image: postgres:latest
    volumes:
      - postgis-data:/var/lib/postgresql
      - $PWD/docker/postgres_scripts/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    # env_file:
    #   - envs/postgres.env
    environment:
        POSTGRES_DB: "drip"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "lolkek"
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus:/etc/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    user: "grafana"
    depends_on:
      - prometheus
    ports:
      - 3000:3000