version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: cd cmd/dripapp && go build
      
      - store_artifacts:
          path: /tmp/artifacts
  unit-tests:
      working_directory: ~/repo
      docker:
        - image: circleci/golang:1.16
      steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: cd cmd/dripapp && go build
      - run:
          name: "making test-results folder"
          command: |
                mkdir test-results && cd test-results && mkdir go && pwd
                ls
                pwd
      - run:
            name: "Running tests and storing under test-results folder"
            command: |
                ls 
                go get gotest.tools/gotestsum
                go run gotest.tools/gotestsum --junitfile test-results/go/unit-tests.xml
      - store_test_results:
                path: test-results
  linter:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: cd cmd/dripapp && go build
      
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: test-results
      
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
