scrape_configs:
  - job_name: 'main'
    scheme: https
    tls_config:
        insecure_skip_verify: true
    static_configs:
      - targets: ['api.monkeys.team:8000']

  - job_name: 'chat'
    scheme: https
    tls_config:
        insecure_skip_verify: true
    static_configs:
      - targets: ['api.monkeys.team:8001']

  - job_name: 'auth'
    scheme: https
    tls_config:
        insecure_skip_verify: true
    static_configs:
      - targets: ['api.monkeys.team:8002']

  - job_name: 'system'
    static_configs:
      - targets: ['api.monkeys.team:9100']