global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'main'
    static_configs:
      - targets: ['2021_2_monkeys_backend-main_service-1:8000']


  - job_name: 'chat'
    static_configs:
      - targets: ['2021_2_monkeys_backend-main_service-1:8001']

  - job_name: 'system'
    static_configs:
      - targets: ['2021_2_monkeys_backend-node-exporter-1:9100']
