basePath: api/v1
definitions:
  main.LoginUser:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: https://api.ijia.me
info:
  contact: {}
  description: API for Drip.
  termsOfService: http://swagger.io/terms/
  title: Drip API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: log in
      parameters:
      - description: data for login
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: LogIn
swagger: "2.0"
