name: Deployment

on:
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
    
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Install Dependecies
        run: go get ./...

      - name: Go mod tidy
        run: go mod tidy

      - name: Build
        run: cd cmd/dripapp && go build
  
  test:
  
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
    
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Install Dependecies
        run: go get ./...

      - name: Go mod tidy
        run: go mod tidy

      - name: Build
        run: cd cmd/dripapp && go build

      - name: Test
        run: make test

  deploy:
  
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
    
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Install Dependecies
        run: go get ./...

      - name: Go mod tidy
        run: go mod tidy

      - name: Build
        run: cd cmd/dripapp && go build

      - name: Test
        run: make test

      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.DEPLOYMENT_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"

    
      - run: cd static && sudo rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --omit-dir-times --no-perms --delete . clown@drip.monkeys.team:~/../back

  


  
  