name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go mod tidy
        run: go mod tidy

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build
        run: docker build -t dependencies -f ./docker/builder.Dockerfile .  &&
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/drip_tarantool:${{github.sha}} -f ./docker/drip_tarantool.Dockerfile . &&
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/main_service:${{github.sha}} -f ./docker/main_service.Dockerfile . &&
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat_service:${{github.sha}} -f ./docker/chat_service.Dockerfile . &&
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth_service:${{github.sha}} -f ./docker/auth_service.Dockerfile .

      - name: Publish docker image
        run:
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/drip_tarantool:${{github.sha}} &&
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/main_service:${{github.sha}} &&
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat_service:${{github.sha}} &&
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth_service:${{github.sha}}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependecies
        run: go get ./...

      - name: Go mod tidy
        run: go mod tidy

      - name: Build
        run: cd cmd/dripapp && go build

      - name: Test
        run: make test

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup deployment ssh key
        run: set -eu &&
              mkdir "$HOME/.ssh" &&
              echo "${{ secrets.DEPLOYMENT_KEY }}" > "$HOME/.ssh/key" &&
              chmod 600 "$HOME/.ssh/key"
      
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: drip.monkeys.team
          username: clown
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            cd ~/../back
            git pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/drip_tarantool:${{github.sha}} &&
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/main_service:${{github.sha}} &&
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chat_service:${{github.sha}} &&
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/auth_service:${{github.sha}}
            sudo docker rm -vf $(docker ps -a -q) || true
            sudo make deploy-run

            
